### PR TITLE
signature: traverse error chain, build multiline error messages

### LINKED ISSUE #34: Verification errors include too little information to diagnose
With the current git main (780760c3fd8b0f769a58ba955362e35bdc38f8a7), run `cargo update` to pull in sequoia-openpgp 2.1.0 and run `cargo test`. `signature::tests::verification_helper_check` will fail because the new "eddsa" policy keyword is not in the crypto-policies yet, but the error printed is too brief:

```console
---- signature::tests::verification_helper_check stdout ----

thread 'signature::tests::verification_helper_check' (34333) panicked at src/signature.rs:1377:14:
verify should succeed: Multiple signature errors: [Subkey of 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE not bound: primary key, Subkey of 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE not bound: primary key]

```

If you do the same with `sequoia-sqv`, it prints:

```console
cargo run -- --keyring ../podman-sequoia/src/data/with-passphrase.pub --message ../podman-sequoia/src/data/double-signed.signature --output a
Signing key on 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE is not bound:
           primary key
  because: Policy rejected asymmetric algorithm
  because: EdDSA is not considered secure
Signing key on 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE is not bound:
           primary key
  because: Policy rejected asymmetric algorithm
  because: EdDSA is not considered secure
```

We probably want to port a similar logic to traverse the error chain as in https://gitlab.com/sequoia-pgp/sequoia-sqv/-/blob/aef381070150a5bc076d178017bc4d375834fc11/src/sqv.rs#L130.

### PR DESCRIPTION
**Pull request by t184256**
Example output with this change:
```
$ cargo update sequoia-openpgp --precise 2.1.0
$ cargo update sequoia-policy-config --precise 0.8.0
$ cargo test signature::tests::verification_helper_check
...
thread 'signature::tests::verification_helper_check' (550280) panicked at src/signature.rs:1414:14:
verify should succeed: Multiple signature errors:
Signing key on 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE is not bound:
           primary key
  because: Policy rejected asymmetric algorithm
  because: EdDSA is not considered secure
Signing key on 1F5825285B785E1DB13BF36D2D11A19ABA41C6AE is not bound:
           primary key
  because: Policy rejected asymmetric algorithm
  because: EdDSA is not considered secure
...
```

While the implementation mimics the output of sequoia-sqv, and I've referred to its error printing implementation heavily while writing this, it ain't doing anything particularly creative here, so that should be fair use.

Resolves: #34

### CODE REVIEW

**Comment by t184256** [comment]
(138f8f0...44cd840 is just a Signed-off-by)

File: src/signature.rs [hunk 1]
```diff
@@ -303,14 +303,51 @@ impl<'a> VerificationHelper for Helper<'a> {
...
     }
 }
 
+fn pretty_error_chain(err: &anyhow::Error) -> String {
+    let causes = err
+        .chain()
+        .skip(1)
+        .map(|cause| format!("  because: {}", cause));
+    format!(
+        "           {}\n{}",
```
Comment (ueno) [inline src/signature.rs]:
```suggestion
        "           {err}\n{}",
```
Also, I wonder if the caller might be a better place to indent the whole text?

**Review by ueno — COMMENTED** [review]
Small nit; otherwise it looks ok. Thank you.

File: src/signature.rs (hunk 1 above)
Comment (t184256) [reply src/signature.rs]: Thanks for the tip on using names from the scope. Moved the indenting to the caller.

**Review by ueno — COMMENTED** [review]
Functionality wise, this looks OK. I hope, in the future, `pretty_function` can be simply something like:
```rust
fn pretty_error(verification_error: &VerificationError) -> String {
    if let Some(source) = verification_error.source() {
        let causes = anyhow::Chain::new(source)
            .skip(1)
            .map(|cause| format!("\tbecause: {cause}"))
            .collect::<Vec<_>>()
            .join("\n");
        format!("{verification_error}:\n{causes}")
    } else {
        verification_error.to_string()
    }
}
```
Apparently this is currently not possible as [VerificationError](https://gitlab.com/sequoia-pgp/sequoia/-/blob/46b1ccdf72edb4eddcd7e73e33f71cf6fd9901dc/openpgp/src/parse/stream.rs#L332) doesn't override [source](https://doc.rust-lang.org/std/error/trait.Error.html#method.source), meaning that it always returns None.

@mtrmac just in case, none of container-libs and skopeo/podman tests relies on the error messages, right?

**Comment by ueno** [comment]
Filed https://gitlab.com/sequoia-pgp/sequoia/-/merge_requests/1807 FWIW.

**Review by ueno — APPROVED** [review]

**Comment by mtrmac** [comment]
> @mtrmac just in case, none of container-libs and skopeo/podman tests relies on the error messages, right?

I think they might, but we’ll deal with that when we update. (The GPG backend uses different error texts anyway.) Thanks for the heads-up!

On a general note, it’s not very well defined whether Go error values can be multi-line strings, and with the widespread practice of wrapping errors by adding prefixes, precise formatting is not _reliably_ possible. In practice, multi-line error messages do show up in other places, and things seem to work well enough.
